CREATE DATABASE ONLINE_MEDICAL_BOOKING;

USE ONLINE_MEDICAL_BOOKING;


CREATE TABLE USER_CUSTOMERS (
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
LOGIN_NAME NVARCHAR(200) NOT NULL UNIQUE,
PASSWORD NVARCHAR(200) NOT NULL
)


INSERT INTO USER_CUSTOMERS (LOGIN_NAME, PASSWORD)
VALUES 
(N'john_doe', N'password123'),
(N'jane_smith', N'mypassword'),
(N'admin', N'admin123'),
(N'customer01', N'123456'),
(N'test_user', N'test@2025');


SELECT  * FROM USER_CUSTOMERS;